### ISSUE TITLE
2 column support (using col-md-6 not working)

### ISSUE THREAD

**Issue by kstott** [peterkelly/react-jsonschema-form-bs4#6]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
this code:
`import React, {Component} from "react";
import "bootstrap/dist/css/bootstrap.min.css"
import Form from "react-jsonschema-form-bs4";

const schema = {
    title: "Todo",
    type: "object",
    required: ["title"],
    properties: {
        title: {type: "string", title: "Title", default: "A new task"},
        title2: {type: "string", title: "Title2", default: "A new task"},
        done: {type: "boolean", title: "Done?", default: false}
    } 
};

const uiSchema = {
    title: {
        classNames: "col-md-6"
    },
    title2: {
        classNames: "col-md-6"
    }
}

const log = (type) => console.log.bind(console, type);

export class FormTest extends Component {
    render() {
        return <Form
            schema={schema}
            uiSchema={uiSchema}
            onChange={log("changed")}
            onSubmit={log("submitted")}
            onError={log("errors")}/>
    }
}`
[Description of the bug or feature]

Presents as a 1-column layout. If you substitute the original forms library and bootstrap 3 - it presents as a 2 column layout.

I think I know bootstrap grid system well - but cannot figure out how to get a 2-column layout with your version. Any feedback would be very appreciated.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

2 column layout
#### Actual behavior

[What actually happened]
1 column layout
### Version
current. 1.5.1
You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by christopherjbaker** [comment]
The actual items that the class gets added to are fieldsets, which cannot be flexbox'd

**Comment by peterkelly** [comment]
I've now deprecated react-jsonschema-form-bs4 since the mainline version now includes Bootstrap 4 as a plugin. See #10.
