### ISSUE TITLE
MAintainability

### ISSUE THREAD

**Issue by C-odes** [peterkelly/react-jsonschema-form-bs4#8]
HEy
I just wondered whether you are maintaining this lib or not?

Using this in a production project and  need to switch from bootstrap 3 to bootstrap 4.  But it lies between switching to this lib or trying to hack my way through css switching classes.

**Comment by peterkelly** [comment]
Sort of. I update it now and then to keep in sync with the latest version of the main version react-json-schema-form, but otherwise haven't done any other changes other than to make sure it works with bootstrap 4.

We are using this library in a production system at my company so it's in my interest to make sure it continues to work reliably and incorporates improvements from the upstream version.

**Comment by C-odes** [comment]
Nice,  I also read that the previous version is working on getting "withTheme" prop to allow personal choice of theme. Are you working on that too? I noticed you were tagged.

**Comment by C-odes** [comment]
And do I have to do anything other than install this version? Any code changes? I already have the previous working, considering you only changed to bootstrap 4 I assume I only need to uninstall the older one and install yours ?

**Comment by peterkelly** [comment]
I'm not involved with theming work, but I'm glad they're doing it. At some point I plan to take a closer look at the theme mechanism. Hopefully it will eventually make this fork unnecessary.

Regarding use of the library, make sure you include the fontawesome CSS, e.g.

```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
```

I just had a look at the app we're using the library in and it also has this in its `index.html`, but I'm not sure if it's still necessary (possibly not, but if you don't see the arrows show up correctly then try adding this code):

```
<style>
    /* From Bootstrap 3 */
    @font-face {
      font-family: 'Glyphicons Halflings';

      src: url('/fonts/glyphicons-halflings-regular.eot');
      src: url('/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('/fonts/glyphicons-halflings-regular.woff') format('woff'), url('/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
    }
    .glyphicon {
      position: relative;
      top: 1px;
      display: inline-block;
      font-family: 'Glyphicons Halflings';
      font-style: normal;
      font-weight: normal;
      line-height: 1;

      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }

    .glyphicon {
      position: relative;
      top: 1px;
      display: inline-block;
      font-family: 'Glyphicons Halflings';
      font-style: normal;
      font-weight: normal;
      line-height: 1;

      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    .glyphicon-arrow-up:before {
      content: "\e093";
    }
    .glyphicon-arrow-down:before {
      content: "\e094";
    }
    .glyphicon-remove:before {
      content: "\e014";
    }
    .glyphicon-plus:before {
      content: "\002b";
    }
</style>
```

**Comment by C-odes** [comment]
Which arrows?

**Comment by C-odes** [comment]
there is a library named react-jsonschema-form-extras
is this compatible with your library?

**Comment by VakarisZ** [comment]
@peterkelly Is there a way to include the icons without CDN? I've tried including styles from `@fortawesome/react-fontawesome` but couldn't get it to work.

**Comment by peterkelly** [comment]
I've now deprecated react-jsonschema-form-bs4 since the mainline version now includes Bootstrap 4 as a plugin. See #10.
